### ISSUE TITLE
ask

### ISSUE THREAD

**Issue by KagaKouko99** [KagaKouko99/Zorro#1]
@anaklayangan kak nanya klo ini https://github.com/adsbypasser/adsbypasser/commit/ee76ccbe2fe326e70f6c11d410525f733a73a209 bisa di implementasikan engga ke universal bypass soalnya pke script adsbypasser ini bisa auto klik smpe menuju ke link tujuan wlupun ada simbol recaptcha google

**Comment by anaklayangan** [comment]
I have tried that script but the result is bad request.
If you want to implement it on universal bypass, here's the script.
```
ifElement("#generater",()=> {
    setTimeout(()=>{
        document.querySelector("#generater").click()
        setTimeout(()=>document.querySelector("#showlink").click(),2000)
    },1000)
})
```
You can try it on Custom Bypasses.

**Comment by KagaKouko99** [comment]
@anaklayangan ok thank you so much 
i change timeout 1000 to 4000 to avoid bad request it's work really well

**Comment by KagaKouko99** [comment]
@anaklayangan and if the type is like this how to implement?
example : http://lifesurance.info/?id=K3cvb3VPVzJkSnhSZWhwejRhdkZING1QcjJSTWlNdHliSDVMNFY3RHE0cUdSQU9uLzIwZ1RPWkVRUE5DRXR5eitBVVBPbFg4MlJHS0dNNG5KMC9Ya1Q0Mmlac3RtdzFFYTdZeUloNGw5SzAyZ1BxdkR3c1E3R05tU2tIYmRGa1Q=

http://bermedsos.com/?id=SFVkQ3pPWUt1ektOTUNDMFRYWk80RmJ3Z05QeVhBRS95ejZlTnN2VThySVlzUFJqaC9LcEV4bjhVUVdISXIycHdJQ2d5QXVrOFI2NExKZDltdzVQd0xSVkNQZjBpK2VDem9ZbFhSVG5JeTlOSFNnYlk0Z1dJaitVVmxnOWQxWkhhQy9yNG0yQzVnNlVlS0RTa3ZXU0cvM0lmVjIvTXNZS21WQTFMK0tVa2p3RFdINHVJamJZTVJ5RHhDaFdsaDNyektBWUVQUmNtZUV3S2Yxb1lVZnNRQT09

**Comment by anaklayangan** [comment]
```
ensureDomLoaded(()=>
{
    if(document.querySelector("#generater")){
        setTimeout(()=>{
            document.querySelector("#generater").click()
            setTimeout(()=>document.querySelector("#showlink").click(),6000)
        },2000)
    }
    else ifElement("#showlink",s=>{
        setTimeout(()=>s.click(),2000)
    })
})
```

**Comment by KagaKouko99** [comment]
Thanks a lot it works really well.i appreciate it
i changed setTimeout to 5000 to avoid bad request
